/* Generated by tools/render_sheets.py - edit tools/projects_src.py instead. */
window.CATEGORIES = [
  "Steel Structures",
  "Commercial & Industrial",
  "Connections & Anchorage",
  "Foundations & Special Structures",
  "Residential & ADU",
  "Additions, Remodels & Repairs",
  "Structural Analysis & Modelling"
];
window.PROJECTS = [
  {
    "id": "steel-tubular-building-missouri",
    "title": "40′ × 60′ Fully Enclosed Steel Tubular Building",
    "city": "Pleasant Hill, MO",
    "category": "Steel Structures",
    "featured": true,
    "size": "40′ × 60′ · 16′ eave · 2,400 sq ft",
    "summary": "Engineered tubular-steel building designed for 140 mph wind: trusses, columns, purlins, base-rail anchorage and slab foundation.",
    "scope": [
      "Design loads: 140 mph ultimate wind, Exposure C, Risk Category II, 5 psf ground snow, 12 psf roof live",
      "Foundation plan with 12\" deep footers, column layout, truss layout and purlin layout",
      "Double-leg tubular columns (2.5×2.5×14 ga), trusses and a full member schedule",
      "Main wind force resisting system, components & cladding and base-rail anchorage",
      "Connection details and typical wall framing sections"
    ],
    "codes": [
      "2024 IBC / IRC",
      "AISC 360-22",
      "ACI 318-19"
    ],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/steel-tubular-building-missouri/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/steel-tubular-building-missouri/s01.webp",
        "caption": "Truss layout and section front · S7",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-building-missouri/s02.webp",
        "caption": "Foundation plan · S3",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-building-missouri/s03.webp",
        "caption": "Column layout plan · S4",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-building-missouri/s04.webp",
        "caption": "Truss layout plan · S5",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-building-missouri/s05.webp",
        "caption": "Purlin layout plan · S6",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-building-missouri/s06.webp",
        "caption": "Section side and member schedule · S8",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-building-missouri/s07.webp",
        "caption": "Typical details · S9",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-building-missouri/s08.webp",
        "caption": "Connection details · S11",
        "portrait": false
      }
    ]
  },
  {
    "id": "steel-tubular-carport-texas",
    "title": "40′ × 80′ Steel Tubular Carport Building",
    "city": "Riviera, TX",
    "category": "Steel Structures",
    "size": "40′ × 80′ · 16′ eave · 3,200 sq ft",
    "summary": "Long-span tubular-steel carport / utility building designed for 145 mph wind, with laced columns, trusses, purlins and slab foundation.",
    "scope": [
      "Design loads: 145 mph ultimate wind, Exposure C, Risk Category II, 5 psf ground snow",
      "Foundation, column, truss and purlin layout plans for an 80′ length",
      "Ladder-leg / laced tubular columns and trusses with full member legend",
      "Truss-to-post and roof-rafter connection details"
    ],
    "codes": [
      "2024 IBC / IRC",
      "AISC 360-22",
      "ACI 318-19"
    ],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/steel-tubular-carport-texas/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/steel-tubular-carport-texas/s01.webp",
        "caption": "Truss layout and section front · S7",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-carport-texas/s02.webp",
        "caption": "Foundation plan · S3",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-carport-texas/s03.webp",
        "caption": "Column layout plan · S4",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-carport-texas/s04.webp",
        "caption": "Truss layout plan · S5",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-carport-texas/s05.webp",
        "caption": "Purlin layout plan · S6",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-carport-texas/s06.webp",
        "caption": "Section side and typical truss details · S8",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-carport-texas/s07.webp",
        "caption": "Typical details · S9",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-tubular-carport-texas/s08.webp",
        "caption": "Connection details · S11",
        "portrait": false
      }
    ]
  },
  {
    "id": "steel-porch-louisiana",
    "title": "Steel Porch with Standing-Seam Metal Roof",
    "city": "St. George, LA",
    "category": "Steel Structures",
    "size": "Attached porch · galvanized steel frame",
    "summary": "A new galvanized-steel porch attached to an existing house, with 4×4 steel posts and beams, C-channel rafters and a standing-seam metal roof.",
    "scope": [
      "Porch foundation plan, layout plan and framing plan",
      "4×4×11 ga galvanized steel posts and beams; 2×4×14 ga C-channel rafters",
      "Post-to-base-plate, beam-to-column and rafter-to-beam connections",
      "Roof-to-existing-wall ledger and receiver details; 26 ga standing-seam roof system"
    ],
    "codes": [],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/steel-porch-louisiana/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/steel-porch-louisiana/s01.webp",
        "caption": "Porch framing plan",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-porch-louisiana/s02.webp",
        "caption": "Porch foundation plan",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-porch-louisiana/s03.webp",
        "caption": "Porch layout plan",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-porch-louisiana/s04.webp",
        "caption": "Porch sections",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-porch-louisiana/s05.webp",
        "caption": "Footing and post-base details",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-porch-louisiana/s06.webp",
        "caption": "Steel connection details",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-porch-louisiana/s07.webp",
        "caption": "Roof system isometric",
        "portrait": false
      }
    ]
  },
  {
    "id": "open-air-pavilion-mcfarland",
    "title": "Open-Air Pavilion on HSS Posts",
    "city": "McFarland, CA",
    "category": "Steel Structures",
    "size": "Open-sided gable roof structure",
    "summary": "A free-standing open-air pavilion carried on HSS posts, with grade beams, large timber beams and a framed gable roof.",
    "scope": [
      "Foundation schedule: F1 30\"×30\"×18\" footings with (4) #4 top and (4) #5 bottom each way; 18\"W × 18\"D grade beam",
      "HSS 8×8×³⁄₁₆ posts with cap connections to beams at corners; 3/4\"Ø anchor bolts on 12\"×12\"×¾\" plates",
      "DF#2 beams (6×10 and 6×16), 2×8 rafters @ 24\" O.C. and 2×10 ridge beam",
      "Building sections, roof framing and connection details"
    ],
    "codes": [
      "ACI 318"
    ],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/open-air-pavilion-mcfarland/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/open-air-pavilion-mcfarland/s01.webp",
        "caption": "Building sections · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/open-air-pavilion-mcfarland/s02.webp",
        "caption": "Foundation plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/open-air-pavilion-mcfarland/s03.webp",
        "caption": "Post layout plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/open-air-pavilion-mcfarland/s04.webp",
        "caption": "Roof framing details · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/open-air-pavilion-mcfarland/s05.webp",
        "caption": "Footing and post-base details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/open-air-pavilion-mcfarland/s06.webp",
        "caption": "Beam connection details · S-6",
        "portrait": false
      }
    ]
  },
  {
    "id": "steel-truss-canopy-texas",
    "title": "Steel Truss Canopy on Wide-Flange Columns",
    "city": "Leonard, TX",
    "category": "Steel Structures",
    "featured": true,
    "size": "Mono-slope steel truss roof · W12 columns",
    "summary": "A mono-slope steel roof structure: HSS trusses spanning between W12×30 columns and W10×30 beams tied to existing masonry walls, analysed in Tekla Structural Designer.",
    "scope": [
      "W12×30 columns and W10×30 (A992) beams with bolted plate connections to the existing masonry walls",
      "HSS 2½×2½×³⁄₁₆ truss chords and webs, HSS 5×5×³⁄₁₆ members and HSS 2×2×⅛ purlins",
      "3D analysis and member design of the truss frame in Tekla Structural Designer",
      "Column base plates, anchor bolts and pad footings PB1–PB4 (3′×3′ and 4′×4′, 12″ deep)",
      "Layout plan, elevations, truss / purlin layout and foundation plan"
    ],
    "codes": [
      "AISC 360",
      "ACI 318-14",
      "ASCE 7-16"
    ],
    "software": [
      "Tekla Structural Designer",
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/steel-truss-canopy-texas/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/steel-truss-canopy-texas/s01.webp",
        "caption": "Elevations and I-beam-to-wall installation · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-truss-canopy-texas/s02.webp",
        "caption": "Layout plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-truss-canopy-texas/s03.webp",
        "caption": "Truss, beam and purlin layout · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-truss-canopy-texas/s04.webp",
        "caption": "Foundation plan and footing schedule · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-truss-canopy-texas/s05.webp",
        "caption": "Tekla Structural Designer model and analysis summary",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-truss-canopy-texas/s06.webp",
        "caption": "Calculation · column base plate design",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-truss-canopy-texas/s07.webp",
        "caption": "Calculation · anchor bolt design",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-truss-canopy-texas/s08.webp",
        "caption": "Calculation · pad footing design",
        "portrait": true
      }
    ]
  },
  {
    "id": "metal-building-gulf-coast-texas",
    "title": "20′ × 36′ Metal Building for 150 mph Wind",
    "city": "Groves, TX",
    "category": "Steel Structures",
    "size": "20′ × 36′ · 12′ eave · 720 sq ft",
    "summary": "A tubular-steel metal building on the Texas Gulf Coast designed for a 150 mph ultimate wind speed, with single-leg frames, purlins, slab and base-rail anchorage.",
    "scope": [
      "Design criteria: IBC 2021, 150 mph ultimate wind (Exposure C), 20 psf design snow load",
      "Foundation plan with strip footing, column, rafter and purlin layout plans",
      "Single-leg 2½″×2½″×14 ga tubular columns and rafters at 5′-0″ frame spacing",
      "Side-wall framing sections, slab / grade anchorage and connection details"
    ],
    "codes": [
      "IBC 2021",
      "ASCE 7",
      "AISC 360",
      "ACI 318"
    ],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/metal-building-gulf-coast-texas/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/metal-building-gulf-coast-texas/s01.webp",
        "caption": "Rafter layout for 150 mph wind · section front",
        "portrait": false
      },
      {
        "src": "assets/projects/metal-building-gulf-coast-texas/s02.webp",
        "caption": "Building elevations",
        "portrait": false
      },
      {
        "src": "assets/projects/metal-building-gulf-coast-texas/s03.webp",
        "caption": "Foundation plan and specifications",
        "portrait": false
      },
      {
        "src": "assets/projects/metal-building-gulf-coast-texas/s04.webp",
        "caption": "Column layout plan",
        "portrait": false
      },
      {
        "src": "assets/projects/metal-building-gulf-coast-texas/s05.webp",
        "caption": "Purlin layout plan",
        "portrait": false
      },
      {
        "src": "assets/projects/metal-building-gulf-coast-texas/s06.webp",
        "caption": "Section side and member schedule",
        "portrait": false
      },
      {
        "src": "assets/projects/metal-building-gulf-coast-texas/s07.webp",
        "caption": "Slab and anchorage details",
        "portrait": false
      },
      {
        "src": "assets/projects/metal-building-gulf-coast-texas/s08.webp",
        "caption": "Connection details",
        "portrait": false
      }
    ]
  },
  {
    "id": "steel-portal-frame-mezzanine",
    "title": "Pre-Engineered Steel Building with Mezzanine Floors",
    "city": "Agra, India",
    "category": "Steel Structures",
    "size": "≈ 27 m × 40 m · 12.6 m to ridge · 2 mezzanine levels",
    "summary": "A pre-engineered steel building with two internal mezzanine levels, designed to Indian Standards: tapered built-up portal frames, ISMB / ISMC secondary members, column and footing layouts and base connections.",
    "scope": [
      "STAAD.Pro 3D model: tapered built-up portal frames, mezzanine floors at +3.05 m and +6.18 m, ridge at +12.57 m",
      "Seismic loads to IS 1893 (Part 1):2016 — Zone III, importance factor 1.2, R = 5, medium soil",
      "Wind loads to IS 875 (Part 3):2015 — basic wind speed 47 m/s",
      "Member checks to IS 800:2007, with ISMB 200 and ISMC 125 secondary members",
      "Column layout, mezzanine and roof framing plans, and portal-frame elevations on each grid line",
      "Footing layout with footing schedule, base plates and anchor-bolt details"
    ],
    "codes": [
      "IS 800:2007",
      "IS 875 (Part 3):2015",
      "IS 1893 (Part 1):2016"
    ],
    "software": [
      "STAAD.Pro",
      "AutoCAD"
    ],
    "cover": "assets/projects/steel-portal-frame-mezzanine/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/steel-portal-frame-mezzanine/s01.webp",
        "caption": "Elevation on grid 1 — portal frame with mezzanine",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-portal-frame-mezzanine/s02.webp",
        "caption": "STAAD.Pro 3D model — wireframe and rendered views",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-portal-frame-mezzanine/s03.webp",
        "caption": "Elevation on grid B",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-portal-frame-mezzanine/s04.webp",
        "caption": "Column layout — ground level",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-portal-frame-mezzanine/s05.webp",
        "caption": "Framing plan at mezzanine level",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-portal-frame-mezzanine/s06.webp",
        "caption": "Roof plan and general notes",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-portal-frame-mezzanine/s07.webp",
        "caption": "Elevation on grid I",
        "portrait": false
      },
      {
        "src": "assets/projects/steel-portal-frame-mezzanine/s08.webp",
        "caption": "Footing layout — ground level",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-portal-frame-mezzanine/s09.webp",
        "caption": "Base plate and connection details, footing schedule",
        "portrait": false
      }
    ]
  },
  {
    "id": "restaurant-remodel-escondido",
    "title": "Restaurant Interior Remodel",
    "city": "Escondido, CA",
    "category": "Commercial & Industrial",
    "size": "4,730 sq ft restaurant",
    "summary": "Structural support for the interior remodel of an existing restaurant, including new wall layout, foundation and steel-framing details.",
    "scope": [
      "Proposed wall layout plan",
      "Foundation plan",
      "Typical, section and wall details (including steel members)"
    ],
    "codes": [
      "2022 CRC",
      "ASCE 7-16",
      "ACI 318-14",
      "AISC 360-16"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/restaurant-remodel-escondido/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/restaurant-remodel-escondido/s01.webp",
        "caption": "Proposed wall layout plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/restaurant-remodel-escondido/s02.webp",
        "caption": "Foundation plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/restaurant-remodel-escondido/s03.webp",
        "caption": "Typical details · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/restaurant-remodel-escondido/s04.webp",
        "caption": "Typical section details · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/restaurant-remodel-escondido/s05.webp",
        "caption": "Typical wall details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/restaurant-remodel-escondido/s06.webp",
        "caption": "Calculation sheet (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "storage-building-escondido",
    "title": "New Storage Building for Event Hall",
    "city": "Escondido, CA",
    "category": "Commercial & Industrial",
    "size": "2,250 sq ft",
    "summary": "A new storage building serving an existing event hall: wall layout, foundation, roof trusses and connection details.",
    "scope": [
      "Wall layout plan and wall elevations",
      "Foundation plan",
      "Roof / truss layout and roof-framing connection details",
      "Section and typical details"
    ],
    "codes": [
      "2025 CRC",
      "NDS 2018",
      "ASCE 7-22",
      "ACI 318-14",
      "AISC 360-10"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/storage-building-escondido/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/storage-building-escondido/s01.webp",
        "caption": "Wall layout plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/storage-building-escondido/s02.webp",
        "caption": "Foundation plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/storage-building-escondido/s03.webp",
        "caption": "Roof / truss layout · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/storage-building-escondido/s04.webp",
        "caption": "Section details · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/storage-building-escondido/s05.webp",
        "caption": "Wall elevations · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/storage-building-escondido/s06.webp",
        "caption": "Roof framing connection details · S-6",
        "portrait": false
      },
      {
        "src": "assets/projects/storage-building-escondido/s07.webp",
        "caption": "Typical details · S-7",
        "portrait": false
      },
      {
        "src": "assets/projects/storage-building-escondido/s08.webp",
        "caption": "Calculation sheet (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "campus-storage-building-spring-valley",
    "title": "Campus Storage Building with CMU Wall",
    "city": "Spring Valley, CA",
    "category": "Commercial & Industrial",
    "size": "1,292 sq ft · two storage rooms",
    "summary": "A new two-room storage building adjacent to an existing school building, with strip footings, slab on grade, shear-wall framing and a CMU wall.",
    "scope": [
      "Foundation and grade-slab plan: 24\"W × 18\"D continuous strip footings, 4\" slab on grade",
      "Wall layout, wall elevations and shear-wall connection details",
      "Roof plan and roof-framing details",
      "CMU wall design calculations"
    ],
    "codes": [
      "CBC",
      "ASCE 7-16",
      "NDS 2018",
      "SDPWS",
      "ACI 318-14"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/campus-storage-building-spring-valley/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/campus-storage-building-spring-valley/s01.webp",
        "caption": "Foundation plan and grade slab plan · S-6",
        "portrait": false
      },
      {
        "src": "assets/projects/campus-storage-building-spring-valley/s02.webp",
        "caption": "Wall layout · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/campus-storage-building-spring-valley/s03.webp",
        "caption": "Wall elevations · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/campus-storage-building-spring-valley/s04.webp",
        "caption": "Wall connection details · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/campus-storage-building-spring-valley/s05.webp",
        "caption": "Roof plan · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/campus-storage-building-spring-valley/s06.webp",
        "caption": "Roof framing details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/campus-storage-building-spring-valley/s07.webp",
        "caption": "Calculation sheet · CMU wall (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "cleanroom-partitions-florida",
    "title": "Cleanroom Partition Walls & Steel Door Headers",
    "city": "Brooksville, FL",
    "category": "Commercial & Industrial",
    "featured": true,
    "size": "Manufacturing facility · cold-formed steel",
    "summary": "Structural design of new cleanroom partition walls inside an operating manufacturing facility: cold-formed steel studs, bracing to structure, and steel headers over every door opening.",
    "scope": [
      "Existing and new wall plans, wall elevations and connection details",
      "400S162-54 cold-formed steel studs with 1½″ cold-rolled channel bracing at 4′-0″ O.C.",
      "Steel door headers designed for each opening (D100–D108) to AISC 360",
      "Wall area-load and stud checks to AISI S100 under Florida Building Code wind and seismic provisions"
    ],
    "codes": [
      "Florida Building Code",
      "ASCE 7-16",
      "AISI S100",
      "AISC 360"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/cleanroom-partitions-florida/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/cleanroom-partitions-florida/s01.webp",
        "caption": "New wall plan · A1.1",
        "portrait": false
      },
      {
        "src": "assets/projects/cleanroom-partitions-florida/s02.webp",
        "caption": "Existing wall plan · A1.0",
        "portrait": false
      },
      {
        "src": "assets/projects/cleanroom-partitions-florida/s03.webp",
        "caption": "Wall elevations · A1.2",
        "portrait": false
      },
      {
        "src": "assets/projects/cleanroom-partitions-florida/s04.webp",
        "caption": "Wall elevations · A1.3",
        "portrait": false
      },
      {
        "src": "assets/projects/cleanroom-partitions-florida/s05.webp",
        "caption": "Connection details · A1.4",
        "portrait": false
      },
      {
        "src": "assets/projects/cleanroom-partitions-florida/s06.webp",
        "caption": "Calculation · steel door header (AISC 360)",
        "portrait": true
      },
      {
        "src": "assets/projects/cleanroom-partitions-florida/s07.webp",
        "caption": "Calculation · wall area loads and CFS studs",
        "portrait": true
      }
    ]
  },
  {
    "id": "cold-formed-steel-medical-facility",
    "title": "Cold-Formed Steel Ceiling & Wall Framing",
    "city": "",
    "category": "Commercial & Industrial",
    "size": "Medical facility interior · CFS framing",
    "summary": "Cold-formed steel wall and ceiling framing for a medical-facility interior, with C8×18.75 channel beams, CFS ceiling joists, slab-on-ground foundations and connection details.",
    "scope": [
      "Foundation plan with 4″ slab on ground and ½″Ø adhesive anchors @ 24″ O.C.",
      "Wall layout and elevations for 362S162-68 cold-formed steel stud walls @ 16″ O.C.",
      "Ceiling structural plans with C8×18.75 channels (2 rows #10 screws @ 16″) and 800S200-68 CFS joists",
      "Cold-formed steel details: tracks, bridging, clips and strapping against beam rotation",
      "Calculations for steel beams (AISC 360), CFS joists and studs (AISI S100 / S240) and footings (ACI 318)"
    ],
    "codes": [
      "IBC 2021",
      "ASCE 7-16",
      "AISI S100-16",
      "AISI S240-15",
      "AISC 360-16",
      "ACI 318-14"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/cold-formed-steel-medical-facility/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/cold-formed-steel-medical-facility/s01.webp",
        "caption": "Ceiling structural plan · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/cold-formed-steel-medical-facility/s02.webp",
        "caption": "Ceiling joist layout · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/cold-formed-steel-medical-facility/s03.webp",
        "caption": "Foundation plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/cold-formed-steel-medical-facility/s04.webp",
        "caption": "Wall layout plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/cold-formed-steel-medical-facility/s05.webp",
        "caption": "Wall elevations · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/cold-formed-steel-medical-facility/s06.webp",
        "caption": "Cold-formed steel details · S-6",
        "portrait": false
      },
      {
        "src": "assets/projects/cold-formed-steel-medical-facility/s07.webp",
        "caption": "Ceiling / roof framing details · S-7",
        "portrait": false
      },
      {
        "src": "assets/projects/cold-formed-steel-medical-facility/s08.webp",
        "caption": "Calculation · C8×18.75 steel beam (AISC 360)",
        "portrait": true
      },
      {
        "src": "assets/projects/cold-formed-steel-medical-facility/s09.webp",
        "caption": "Calculation · cold-formed steel ceiling joist",
        "portrait": true
      },
      {
        "src": "assets/projects/cold-formed-steel-medical-facility/s10.webp",
        "caption": "Calculation · cold-formed steel wall studs",
        "portrait": true
      }
    ]
  },
  {
    "id": "g3-multipurpose-hall-karnal",
    "title": "G+3 RCC Multipurpose Hall",
    "city": "Karnal, Haryana, India",
    "category": "Commercial & Industrial",
    "featured": false,
    "size": "G+3 · RCC moment frame · 10 × 2 bays",
    "summary": "STAAD.Pro analysis, IS 456 concrete design and structural drawings for a ground-plus-three RCC multipurpose hall, prepared for government approval submission.",
    "scope": [
      "3D RCC frame model in STAAD.Pro V8i with dead, live and load-combination cases",
      "Beam, column and footing design to IS 456 (e.g. 375 × 600 mm beams with 4-#12 top and bottom bars)",
      "Layout plans: column grid, footing layout, plinth-beam and floor-beam framing (S-01)",
      "Plinth-beam reinforcement details and bar schedule (S-02)",
      "Isolated footing reinforcement plans, sections and footing schedule (S-05)",
      "Design basis on the drawings: M30 concrete, Fe 500 HYSD steel, SBC 150 kN/m² at 2.0 m depth, clear covers 40 / 30 / 20 / 50 mm (column / beam / slab / footing)"
    ],
    "codes": [
      "IS 456"
    ],
    "software": [
      "STAAD.Pro V8i"
    ],
    "sheets": [
      {
        "src": "assets/projects/g3-multipurpose-hall-karnal/cover.webp",
        "caption": "3D structural model",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-multipurpose-hall-karnal/s01.webp",
        "caption": "STAAD.Pro beam concrete design to IS 456",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-multipurpose-hall-karnal/s02.webp",
        "caption": "Layout plans · S-01",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-multipurpose-hall-karnal/s03.webp",
        "caption": "Plinth-beam reinforcement details · S-02",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-multipurpose-hall-karnal/s04.webp",
        "caption": "Footing reinforcement details · S-05",
        "portrait": false
      }
    ],
    "cover": "assets/projects/g3-multipurpose-hall-karnal/cover.webp",
    "coverIndex": 0
  },
  {
    "id": "public-toilet-block-india",
    "title": "Public Toilet Block — RCC Design & Detailing",
    "city": "India",
    "category": "Commercial & Industrial",
    "featured": false,
    "size": "Single-storey RCC frame with roof water tanks",
    "summary": "Structural design and reinforcement detailing for a government public-toilet block: RCC frame, isolated footings, beams and roof slab carrying overhead water tanks.",
    "scope": [
      "3D frame and reinforcement models of columns, beams and slabs",
      "Footing layout, column and footing reinforcement details, column schedule and bar-bending schedule",
      "Plinth-beam, roof-beam and roof-slab reinforcement layouts and sections",
      "Coordination with the architectural plans, elevations and sections",
      "Design basis on the drawings: M25 concrete, Fe 500 steel; roof tiles to IS 654 and waterproofing to IS 1346"
    ],
    "codes": [
      "IS 654",
      "IS 1346"
    ],
    "software": [],
    "sheets": [
      {
        "src": "assets/projects/public-toilet-block-india/cover.webp",
        "caption": "3D structural frame model",
        "portrait": false
      },
      {
        "src": "assets/projects/public-toilet-block-india/s01.webp",
        "caption": "Reinforcement model of columns, beams and slabs",
        "portrait": false
      },
      {
        "src": "assets/projects/public-toilet-block-india/s02.webp",
        "caption": "Architectural plans, elevations and sections",
        "portrait": false
      },
      {
        "src": "assets/projects/public-toilet-block-india/s03.webp",
        "caption": "Footing layout, column details and bending schedule",
        "portrait": false
      },
      {
        "src": "assets/projects/public-toilet-block-india/s04.webp",
        "caption": "Beam and slab reinforcement layouts and details",
        "portrait": false
      }
    ],
    "cover": "assets/projects/public-toilet-block-india/cover.webp",
    "coverIndex": 0
  },
  {
    "id": "podium-steel-wall-cover-dubai",
    "title": "Podium Steel Wall Cover — Analysis & Connection Design",
    "city": "Dubai, UAE",
    "category": "Connections & Anchorage",
    "featured": true,
    "size": "4.23 m × 2.98 m chequered-plate cover",
    "summary": "Analysis model and connection design for a steel chequered-plate wall cover on a high-rise podium, including a consultant-comment response and an IDEA StatiCa connection check.",
    "scope": [
      "STAAD.Pro geometry model of the channel / angle frame (CH-1 150×75 channel, AE-1 60×60×5 angle, 4 mm plate)",
      "Section assignment, supports and load application; deflection and member utilisation checks",
      "Fin-plate and base-plate connection design to AISC 360 (LRFD)",
      "CBFEM angle-to-channel connection check in IDEA StatiCa",
      "Load traceability from analysis reactions to connection loads; response to consultant comments"
    ],
    "codes": [
      "AISC 360-10/16 (LRFD)",
      "ACI 318-14/19"
    ],
    "software": [
      "STAAD.Pro",
      "IDEA StatiCa"
    ],
    "cover": "assets/projects/podium-steel-wall-cover-dubai/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/podium-steel-wall-cover-dubai/s01.webp",
        "caption": "STAAD.Pro analysis model views",
        "portrait": true
      },
      {
        "src": "assets/projects/podium-steel-wall-cover-dubai/s02.webp",
        "caption": "Section assignment and supports",
        "portrait": true
      },
      {
        "src": "assets/projects/podium-steel-wall-cover-dubai/s03.webp",
        "caption": "Load application on the model",
        "portrait": true
      },
      {
        "src": "assets/projects/podium-steel-wall-cover-dubai/s04.webp",
        "caption": "Analysis results — displacements and reactions",
        "portrait": true
      },
      {
        "src": "assets/projects/podium-steel-wall-cover-dubai/s05.webp",
        "caption": "Connection design summary (AISC 360)",
        "portrait": true
      },
      {
        "src": "assets/projects/podium-steel-wall-cover-dubai/s06.webp",
        "caption": "IDEA StatiCa — angle-to-channel connection model",
        "portrait": true
      },
      {
        "src": "assets/projects/podium-steel-wall-cover-dubai/s07.webp",
        "caption": "IDEA StatiCa — connection check summary",
        "portrait": true
      }
    ]
  },
  {
    "id": "steel-fence-anchorage-dubai",
    "title": "Steel Fence Base-Plate Anchorage",
    "city": "Dubai, UAE",
    "category": "Connections & Anchorage",
    "size": "SC-1 base connection · 4 × M16 anchors",
    "summary": "Mechanical-anchor and base-plate design for a steel mesh fence on a podium slab, from wind loads through anchor-group distribution to an FEM check of the steel connection.",
    "scope": [
      "STAAD model of the fence (SHS 80×80×3 posts, S275) for dead, wind and temperature load combinations",
      "Wind actions per ASCE 7 (48 m/s basic wind speed)",
      "Anchor group design to EN 1992-4: 4 × FAZ II Plus 16/160 GS R anchors, hef = 160 mm, cracked C30/37 concrete",
      "200×200×12 mm base plate with triangular stiffeners; FEM verification of the steel connection",
      "400×400×400 mm foundation block, splitting control and installation / field detailing"
    ],
    "codes": [
      "EN 1992-4",
      "ASCE 7",
      "AISC 360-10"
    ],
    "software": [
      "STAAD.Pro",
      "fischer C-FIX"
    ],
    "cover": "assets/projects/steel-fence-anchorage-dubai/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/steel-fence-anchorage-dubai/s01.webp",
        "caption": "Connection visuals — SC-1 detailed connection",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-fence-anchorage-dubai/s02.webp",
        "caption": "STAAD fence model and wind load",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-fence-anchorage-dubai/s03.webp",
        "caption": "3D analysis model and reactions",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-fence-anchorage-dubai/s04.webp",
        "caption": "Base material, attachment and anchor layout",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-fence-anchorage-dubai/s05.webp",
        "caption": "FEM steel connection verification",
        "portrait": true
      },
      {
        "src": "assets/projects/steel-fence-anchorage-dubai/s06.webp",
        "caption": "Connection visuals — typical steel joints",
        "portrait": true
      }
    ]
  },
  {
    "id": "two-level-structure-foundations-georgia",
    "title": "Two-Level Framed Structure — Analysis & Foundations",
    "city": "Fort Valley, GA",
    "category": "Foundations & Special Structures",
    "size": "2 levels · 2,448 sq ft",
    "summary": "A 3D Tekla Structural Designer model of a two-level framed structure, used to derive foundation reactions and design the isolated footings.",
    "scope": [
      "3D analysis model: two levels (1,224 sq ft each), 15′-5″ high, with full load combinations",
      "Seismic loading summary to ASCE 7-16 (Site Class C, Risk Category II)",
      "Foundation reactions exported per load case",
      "Isolated footing analysis and design to ACI 318-14"
    ],
    "codes": [
      "ASCE 7-16",
      "ACI 318-14",
      "AISC 360"
    ],
    "software": [
      "Tekla Structural Designer",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/two-level-structure-foundations-georgia/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/two-level-structure-foundations-georgia/s01.webp",
        "caption": "Tekla Structural Designer 3D model and levels",
        "portrait": true
      },
      {
        "src": "assets/projects/two-level-structure-foundations-georgia/s02.webp",
        "caption": "Seismic loading summary (ASCE 7-16)",
        "portrait": true
      },
      {
        "src": "assets/projects/two-level-structure-foundations-georgia/s03.webp",
        "caption": "Calculation · isolated footing design (ACI 318-14)",
        "portrait": true
      },
      {
        "src": "assets/projects/two-level-structure-foundations-georgia/s04.webp",
        "caption": "Calculation · footing design",
        "portrait": true
      },
      {
        "src": "assets/projects/two-level-structure-foundations-georgia/s05.webp",
        "caption": "Calculation · footing checks",
        "portrait": true
      }
    ]
  },
  {
    "id": "rcc-framed-structure-is456",
    "title": "RCC Framed Structure — Columns, Beams, Slab & Footings",
    "city": "",
    "category": "Foundations & Special Structures",
    "size": "16.4 m × 9.1 m · 4 bays · 3.96 m storey",
    "summary": "Analysis, design and reinforcement detailing of a single-storey reinforced-concrete frame to IS 456: ten columns on isolated footings, beams spanning up to 9.1 m and a one-way slab.",
    "scope": [
      "STAAD.Pro frame model with limit-state load combinations and concrete design to IS 456",
      "Column, beam, slab-panel and footing layout plans",
      "600 × 450 columns with 4-T25 + 8-T20 bars and T8 links — M25 concrete, Fe500 steel, 50 mm cover",
      "300 × 600 beams for the 9.1 m (30 ft) span and 300 × 450 beams for the shorter spans",
      "150 mm one-way slab with alternate bars bent up",
      "2400 × 2400 isolated footings on 150 mm PCC, with plan, sections and reinforcement"
    ],
    "codes": [
      "IS 456:2000"
    ],
    "software": [
      "STAAD.Pro",
      "AutoCAD"
    ],
    "cover": "assets/projects/rcc-framed-structure-is456/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/rcc-framed-structure-is456/s01.webp",
        "caption": "Footing FC1 — plan and sections",
        "portrait": false
      },
      {
        "src": "assets/projects/rcc-framed-structure-is456/s02.webp",
        "caption": "Column schedule, beam sections and one-way slab S1",
        "portrait": true
      },
      {
        "src": "assets/projects/rcc-framed-structure-is456/s03.webp",
        "caption": "Column, beam, footing and slab layout plans",
        "portrait": false
      }
    ]
  },
  {
    "id": "shipping-container-house-australia",
    "title": "Shipping-Container House",
    "city": "Victoria, Australia",
    "category": "Foundations & Special Structures",
    "size": "1 bedroom · container conversion",
    "summary": "Structural report and foundation design for a one-bedroom shipping-container home, from loads to Australian standards through strip footings and container-to-slab anchorage.",
    "scope": [
      "Dead, live and wind load calculations to the AS/NZS 1170 series",
      "Strip footings 600 mm wide × 600 mm deep at 1,000 mm embedment",
      "Container walls anchored to concrete with chemical anchors",
      "Wall stud and roof purlin checks, including deflection",
      "Shower-recess floor modification and waterproofing integration"
    ],
    "codes": [
      "AS/NZS 1170"
    ],
    "software": [
      "AutoCAD"
    ],
    "cover": "assets/projects/shipping-container-house-australia/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/shipping-container-house-australia/s01.webp",
        "caption": "Foundation plan, section and container-to-concrete anchoring",
        "portrait": false
      },
      {
        "src": "assets/projects/shipping-container-house-australia/s02.webp",
        "caption": "Report · load calculations",
        "portrait": true
      },
      {
        "src": "assets/projects/shipping-container-house-australia/s03.webp",
        "caption": "Report · strip footing design",
        "portrait": true
      },
      {
        "src": "assets/projects/shipping-container-house-australia/s04.webp",
        "caption": "Report · footing capacity check",
        "portrait": true
      },
      {
        "src": "assets/projects/shipping-container-house-australia/s05.webp",
        "caption": "Report · shower-recess floor modification",
        "portrait": true
      }
    ]
  },
  {
    "id": "container-coffee-stand",
    "title": "Container Coffee Stand — CFS Walls & Footings",
    "city": "",
    "category": "Foundations & Special Structures",
    "size": "Cold-formed steel walls · strip footings",
    "summary": "Calculations for a container-based coffee stand: cold-formed steel wall studs for each elevation and the strip footings beneath them.",
    "scope": [
      "Front, rear and side walls in 600S162-97 cold-formed steel studs @ 16″ O.C. (12′ walls)",
      "Combined axial and lateral (35 psf) stud checks to AISI S100 (ASD)",
      "Strip footing analysis and design for each wall line (ACI 318)"
    ],
    "codes": [
      "AISI S100-07",
      "ACI 318"
    ],
    "software": [
      "Tekla Tedds"
    ],
    "cover": "assets/projects/container-coffee-stand/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/container-coffee-stand/s01.webp",
        "caption": "Calculation · front wall CFS studs (AISI S100)",
        "portrait": true
      },
      {
        "src": "assets/projects/container-coffee-stand/s02.webp",
        "caption": "Calculation · side wall CFS studs",
        "portrait": true
      },
      {
        "src": "assets/projects/container-coffee-stand/s03.webp",
        "caption": "Calculation · front / rear wall strip footing",
        "portrait": true
      },
      {
        "src": "assets/projects/container-coffee-stand/s04.webp",
        "caption": "Calculation · side wall strip footing",
        "portrait": true
      }
    ]
  },
  {
    "id": "detached-adu-san-diego",
    "title": "Detached Two-Story ADU",
    "city": "San Diego, CA",
    "category": "Residential & ADU",
    "size": "530 sq ft · 2 stories",
    "summary": "Full structural package for a new two-story detached ADU (265 sq ft per floor): foundation, floor and roof framing, shear walls and connection details.",
    "scope": [
      "Foundation, floor joist and roof framing design",
      "Shear wall layout and schedule (2x4 DF-L studs at 16\" O.C., 5/8\" gypsum, 8d nails at 6\" edge / 12\" field, R-19 insulation)",
      "Beam and post sizing",
      "Lateral analysis for wind and seismic loads",
      "Connection details and wall elevations for both floors"
    ],
    "codes": [
      "2022 CBC / CRC",
      "ASCE 7-22",
      "NDS",
      "SDPWS"
    ],
    "software": [
      "ETABS",
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/detached-adu-san-diego/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/detached-adu-san-diego/s01.webp",
        "caption": "2nd floor wall layout plan with wall schedule · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-san-diego/s02.webp",
        "caption": "1st floor wall layout plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-san-diego/s03.webp",
        "caption": "Typical section details · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-san-diego/s04.webp",
        "caption": "Wall details · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-san-diego/s05.webp",
        "caption": "Floor joist plan · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-san-diego/s06.webp",
        "caption": "Foundation plan · S-6",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-san-diego/s07.webp",
        "caption": "Calculation sheet · wood shear wall design (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "two-story-house-spring-valley",
    "title": "New Two-Story Home with Detached Garage",
    "city": "Spring Valley, CA",
    "category": "Residential & ADU",
    "featured": true,
    "size": "1,400 sq ft per floor + 504 sq ft garage",
    "summary": "Complete structural design and permit drawings for a new two-story single-family dwelling and detached garage, with engineered-wood floors and a full calculation report.",
    "scope": [
      "Foundation plan, 1st and 2nd floor framing with LVL beams — B101–B103, (3) 1¾\" × 11⅞\" 2.0E LVL flush beams",
      "TJI-235 floor joists at 16\" O.C., 4×6 posts",
      "Shear wall plan and schedule (1SW1–1SW4), hold-downs and connection details",
      "Detached garage wall, roof and foundation design",
      "Full Tekla Tedds calculation report"
    ],
    "codes": [
      "2025 CBC / CRC",
      "ASCE 7-22",
      "NDS-2024",
      "SDPWS-2021"
    ],
    "software": [
      "ETABS",
      "STAAD.Pro",
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/two-story-house-spring-valley/cover.webp",
    "coverIndex": 2,
    "sheets": [
      {
        "src": "assets/projects/two-story-house-spring-valley/s01.webp",
        "caption": "Foundation plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/two-story-house-spring-valley/s02.webp",
        "caption": "1st floor wall layout plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/two-story-house-spring-valley/s03.webp",
        "caption": "1st floor framing plan · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/two-story-house-spring-valley/s04.webp",
        "caption": "2nd floor framing plan · S-3.1",
        "portrait": false
      },
      {
        "src": "assets/projects/two-story-house-spring-valley/s05.webp",
        "caption": "2nd floor wall layout plan · S-2.1",
        "portrait": false
      },
      {
        "src": "assets/projects/two-story-house-spring-valley/s06.webp",
        "caption": "Roof truss layout plan · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/two-story-house-spring-valley/s07.webp",
        "caption": "Typical foundation details · S-7",
        "portrait": false
      },
      {
        "src": "assets/projects/two-story-house-spring-valley/s08.webp",
        "caption": "Garage foundation plan · S-5",
        "portrait": false
      }
    ]
  },
  {
    "id": "garage-to-adu-san-bernardino",
    "title": "Garage-to-ADU Conversion with Connection Details",
    "city": "San Bernardino, CA",
    "category": "Residential & ADU",
    "size": "446 sq ft conversion",
    "summary": "Structural conversion of an existing attached garage to a code-compliant ADU, with a new ceiling joist system tied to the existing roof framing.",
    "scope": [
      "New ceiling joist system: 2×6 @ 16\" O.C. with Simpson A35 blocking and H2.5A ties to existing rafters",
      "Reinforcement of existing framing; field-verification notes for existing conditions",
      "1-hr fire-rated interior and exterior wall sections per UL U465",
      "Top plate splice details with ST6224 straps and a typical structural detail sheet"
    ],
    "codes": [
      "2022 CBC / CRC",
      "NDS",
      "SDPWS"
    ],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/garage-to-adu-san-bernardino/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/garage-to-adu-san-bernardino/s01.webp",
        "caption": "Typical connection details · S-6",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-san-bernardino/s02.webp",
        "caption": "Foundation plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-san-bernardino/s03.webp",
        "caption": "Wall layout plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-san-bernardino/s04.webp",
        "caption": "Roof framing details · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-san-bernardino/s05.webp",
        "caption": "Ceiling framing plan · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-san-bernardino/s06.webp",
        "caption": "Typical section details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-san-bernardino/s07.webp",
        "caption": "Typical details · S-7",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-san-bernardino/s08.webp",
        "caption": "Typical details · S-8",
        "portrait": false
      }
    ]
  },
  {
    "id": "jadu-permitting-encinitas",
    "title": "As-Built JADU Permitting",
    "city": "Encinitas, CA",
    "category": "Residential & ADU",
    "size": "485 sq ft JADU",
    "summary": "Structural calculations and permit sheets for an as-built junior ADU, verifying shear walls, hold-downs, the roof diaphragm and headers to current code.",
    "scope": [
      "Foundation plan, wall layout with shear wall marks SW1–SW3, roof framing plan",
      "Typical section, wall and 1-hr wall details",
      "Segmented shear wall design with Simpson HDU2 hold-downs",
      "Seismic base shear (ASCE 7-22), roof-to-wall shear transfer and diaphragm check",
      "Interior header and beam checks"
    ],
    "codes": [
      "2025 CBC / CRC",
      "ASCE 7-22",
      "NDS",
      "SDPWS-2021"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/jadu-permitting-encinitas/cover.webp",
    "coverIndex": 1,
    "sheets": [
      {
        "src": "assets/projects/jadu-permitting-encinitas/s01.webp",
        "caption": "Foundation plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/jadu-permitting-encinitas/s02.webp",
        "caption": "Wall layout plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/jadu-permitting-encinitas/s03.webp",
        "caption": "Roof framing plan · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/jadu-permitting-encinitas/s04.webp",
        "caption": "Typical section details · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/jadu-permitting-encinitas/s05.webp",
        "caption": "Typical wall details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/jadu-permitting-encinitas/s06.webp",
        "caption": "Typical details · S-7",
        "portrait": false
      },
      {
        "src": "assets/projects/jadu-permitting-encinitas/s07.webp",
        "caption": "Calculation sheet · wood shear wall design (Tekla Tedds)",
        "portrait": true
      },
      {
        "src": "assets/projects/jadu-permitting-encinitas/s08.webp",
        "caption": "Calculation report · shear wall schedule and seismic design",
        "portrait": true
      }
    ]
  },
  {
    "id": "adu-over-garage-escondido",
    "title": "Attached ADU Above Existing Garage",
    "city": "Escondido, CA",
    "category": "Residential & ADU",
    "size": "New ADU over 485 sq ft garage",
    "summary": "A new attached ADU built on top of an existing garage whose roof is removed, with the ADU walls, shear walls and stair framed into the existing structure.",
    "scope": [
      "ADU wall framing plan and wall elevations",
      "Shear wall details and holdown layout",
      "ADU roof plan",
      "Staircase framing details"
    ],
    "codes": [
      "2022 CRC",
      "NDS",
      "SDPWS",
      "ASCE 7-16"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/adu-over-garage-escondido/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/adu-over-garage-escondido/s01.webp",
        "caption": "ADU wall framing plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-over-garage-escondido/s02.webp",
        "caption": "ADU wall elevations · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-over-garage-escondido/s03.webp",
        "caption": "Shear wall details · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-over-garage-escondido/s04.webp",
        "caption": "ADU roof plan · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-over-garage-escondido/s05.webp",
        "caption": "Staircase details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-over-garage-escondido/s06.webp",
        "caption": "Calculation sheet (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "art-studio-to-adu-poway",
    "title": "Art Studio to ADU Conversion",
    "city": "Poway, CA",
    "category": "Residential & ADU",
    "size": "780 sq ft existing studio",
    "summary": "Conversion of an existing art studio to a permitted ADU, documenting and verifying the existing wall, foundation, roof and ceiling framing.",
    "scope": [
      "Existing wall layout, foundation and roof/truss layout plans",
      "Existing ceiling joist layout and verification",
      "Section details, wall elevations and roof-framing connection details"
    ],
    "codes": [
      "2022 CRC",
      "NDS 2018",
      "ASCE 7-16",
      "ACI 318-14"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/art-studio-to-adu-poway/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/art-studio-to-adu-poway/s01.webp",
        "caption": "Existing wall layout plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/art-studio-to-adu-poway/s02.webp",
        "caption": "Existing foundation plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/art-studio-to-adu-poway/s03.webp",
        "caption": "Existing roof / truss layout · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/art-studio-to-adu-poway/s04.webp",
        "caption": "Existing ceiling joist layout · S-3.1",
        "portrait": false
      },
      {
        "src": "assets/projects/art-studio-to-adu-poway/s05.webp",
        "caption": "Section details · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/art-studio-to-adu-poway/s06.webp",
        "caption": "Wall elevations · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/art-studio-to-adu-poway/s07.webp",
        "caption": "Roof framing connection details · S-6",
        "portrait": false
      }
    ]
  },
  {
    "id": "adu-and-garage-chula-vista",
    "title": "ADU with New Detached Garage",
    "city": "Chula Vista, CA",
    "category": "Residential & ADU",
    "size": "695 sq ft ADU + 2-car garage",
    "summary": "A new ADU with a one-car garage and a separate two-car detached garage, each with its own wall, roof and foundation design.",
    "scope": [
      "Floor joist plan and ADU wall elevations",
      "Shear wall details",
      "ADU roof framing layout",
      "2-car garage wall details and roof framing",
      "Foundation plan"
    ],
    "codes": [
      "2022 CRC",
      "NDS",
      "SDPWS",
      "ASCE 7-16"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/adu-and-garage-chula-vista/cover.webp",
    "coverIndex": 1,
    "sheets": [
      {
        "src": "assets/projects/adu-and-garage-chula-vista/s01.webp",
        "caption": "Floor joist plan · 2",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-and-garage-chula-vista/s02.webp",
        "caption": "ADU wall elevations · 3",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-and-garage-chula-vista/s03.webp",
        "caption": "Shear wall details · 4",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-and-garage-chula-vista/s04.webp",
        "caption": "ADU roof framing layout · 5",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-and-garage-chula-vista/s05.webp",
        "caption": "2-car garage wall details · 6",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-and-garage-chula-vista/s06.webp",
        "caption": "2-car garage roof framing · 7",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-and-garage-chula-vista/s07.webp",
        "caption": "Foundation plan · 8",
        "portrait": false
      }
    ]
  },
  {
    "id": "adu-over-jadu-spring-valley",
    "title": "New Attached ADU Above Existing JADU",
    "city": "Spring Valley, CA",
    "category": "Residential & ADU",
    "size": "420 sq ft",
    "summary": "A new upper-floor ADU added above an existing JADU, with the floor, roof and foundation upgrades needed to carry it.",
    "scope": [
      "Floor joist plan for the new upper floor",
      "Roof framing details",
      "Foundation details"
    ],
    "codes": [
      "2022 CRC",
      "NDS 2018",
      "ACI 318-14"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/adu-over-jadu-spring-valley/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/adu-over-jadu-spring-valley/s01.webp",
        "caption": "Floor joist plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-over-jadu-spring-valley/s02.webp",
        "caption": "Roof framing details · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-over-jadu-spring-valley/s03.webp",
        "caption": "Foundation details · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-over-jadu-spring-valley/s04.webp",
        "caption": "General structural notes · S-0",
        "portrait": false
      },
      {
        "src": "assets/projects/adu-over-jadu-spring-valley/s05.webp",
        "caption": "Calculation sheet (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "garage-to-adu-loft-manteca",
    "title": "RV Garage to ADU with Loft",
    "city": "Manteca, CA",
    "category": "Residential & ADU",
    "size": "620 sq ft ADU + 225 sq ft loft",
    "summary": "Conversion of an existing RV garage into an ADU with a new loft, including the wall framing, shear walls, floor joists and stair.",
    "scope": [
      "ADU wall framing plan and wall elevations",
      "Shear wall details",
      "Loft floor joist plan",
      "Staircase details"
    ],
    "codes": [
      "2022 CRC",
      "NDS 2015",
      "SDPWS"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/garage-to-adu-loft-manteca/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/garage-to-adu-loft-manteca/s01.webp",
        "caption": "ADU wall framing plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-loft-manteca/s02.webp",
        "caption": "ADU wall elevations · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-loft-manteca/s03.webp",
        "caption": "Shear wall details · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-loft-manteca/s04.webp",
        "caption": "Floor joist plan · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-loft-manteca/s05.webp",
        "caption": "Staircase details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-to-adu-loft-manteca/s06.webp",
        "caption": "Calculation sheet (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "detached-adu-el-cajon",
    "title": "Detached ADU",
    "city": "El Cajon, CA",
    "category": "Residential & ADU",
    "size": "1,000 sq ft · 1 story",
    "summary": "A new single-story detached ADU with foundation, shear wall and roof framing design.",
    "scope": [
      "Foundation plan and wall layout plan",
      "ADU roof framing plan",
      "Typical section and wall details",
      "Lateral analysis for wind and seismic loads"
    ],
    "codes": [
      "2025 CBC / CRC",
      "ASCE 7-22",
      "NDS-2024",
      "SDPWS-2021"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/detached-adu-el-cajon/cover.webp",
    "coverIndex": 1,
    "sheets": [
      {
        "src": "assets/projects/detached-adu-el-cajon/s01.webp",
        "caption": "Foundation plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-el-cajon/s02.webp",
        "caption": "Wall layout plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-el-cajon/s03.webp",
        "caption": "ADU roof framing plan · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-el-cajon/s04.webp",
        "caption": "Typical section details · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-el-cajon/s05.webp",
        "caption": "Typical wall details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-el-cajon/s06.webp",
        "caption": "Typical details · S-6",
        "portrait": false
      },
      {
        "src": "assets/projects/detached-adu-el-cajon/s07.webp",
        "caption": "Calculation sheet (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "covered-carport-indian-wells",
    "title": "Covered Carport on CMU Footing",
    "city": "Indian Wells, CA",
    "category": "Residential & ADU",
    "size": "383 sq ft",
    "summary": "A new covered carport attached to an existing house, on a reinforced CMU stem wall and continuous footing.",
    "scope": [
      "Foundation schedule: 8\"×16\" CMU on 18\"W × 10\"D footing, (3) #4 top and bottom, #4 @ 18\" O.C. transverse",
      "Wall layout plan and roof framing plan",
      "Typical sections, footing details and deck / roof details"
    ],
    "codes": [
      "2025 CBC / CRC",
      "ACI 318-19",
      "TMS 402",
      "NDS"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/covered-carport-indian-wells/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/covered-carport-indian-wells/s01.webp",
        "caption": "Foundation layout plan · S1",
        "portrait": false
      },
      {
        "src": "assets/projects/covered-carport-indian-wells/s02.webp",
        "caption": "Wall layout plan · S2",
        "portrait": false
      },
      {
        "src": "assets/projects/covered-carport-indian-wells/s03.webp",
        "caption": "Roof framing plan · S3",
        "portrait": false
      },
      {
        "src": "assets/projects/covered-carport-indian-wells/s04.webp",
        "caption": "Typical sections · S4",
        "portrait": false
      },
      {
        "src": "assets/projects/covered-carport-indian-wells/s05.webp",
        "caption": "Typical footing details · S5",
        "portrait": false
      },
      {
        "src": "assets/projects/covered-carport-indian-wells/s06.webp",
        "caption": "Typical deck / roof details · S6",
        "portrait": false
      }
    ]
  },
  {
    "id": "g1-rcc-residential-building-india",
    "title": "G+1 RCC Residential Building",
    "city": "India",
    "category": "Residential & ADU",
    "featured": false,
    "size": "Ground + 1 · 3.2 m storey height · 22 columns",
    "summary": "Analysis, design and complete reinforcement detailing for a two-storey RCC framed house: STAAD.Pro frame model, STAAD Foundation footings and RCDC detailing.",
    "scope": [
      "3D RCC frame in STAAD.Pro with wall, slab and parapet loads applied to the beams",
      "Shear force, bending moment and support-reaction results for design",
      "22 isolated pad footings (FC1–FC22, 1000 × 900 mm to 1350 × 1200 mm, 300–325 mm deep) with footing schedule and sections",
      "Column schedule and details (230 × 350 and 230 × 400 mm columns), beam schedule and sections (230 × 300 mm beams)",
      "150 mm two-way slabs with reinforcement schedule, bottom-reinforcement layout and section",
      "Design basis: M25 concrete and Fe 500 / Fe 500D bars to IS 1786; main wall 13.98 kN/m, partition 6.08 kN/m, slab dead load 4.75 kN/m², live load 2.0 kN/m²"
    ],
    "codes": [
      "IS 456:2000",
      "IS 875",
      "IS 1893 (Part 1):2016",
      "IS 13920:2016",
      "IS 1786"
    ],
    "software": [
      "STAAD.Pro",
      "STAAD Foundation",
      "RCDC"
    ],
    "sheets": [
      {
        "src": "assets/projects/g1-rcc-residential-building-india/cover.webp",
        "caption": "3D analytical model and rendered frame",
        "portrait": false
      },
      {
        "src": "assets/projects/g1-rcc-residential-building-india/s01.webp",
        "caption": "Shear force, bending moment and base reactions",
        "portrait": false
      },
      {
        "src": "assets/projects/g1-rcc-residential-building-india/s02.webp",
        "caption": "Footing schedule, layout and sections",
        "portrait": false
      },
      {
        "src": "assets/projects/g1-rcc-residential-building-india/s03.webp",
        "caption": "Column schedule and details",
        "portrait": false
      },
      {
        "src": "assets/projects/g1-rcc-residential-building-india/s04.webp",
        "caption": "Column cross-section schedule",
        "portrait": false
      },
      {
        "src": "assets/projects/g1-rcc-residential-building-india/s05.webp",
        "caption": "Beam layout, sections and details",
        "portrait": false
      },
      {
        "src": "assets/projects/g1-rcc-residential-building-india/s06.webp",
        "caption": "Slab schedule, bottom-reinforcement layout and section",
        "portrait": false
      }
    ],
    "cover": "assets/projects/g1-rcc-residential-building-india/cover.webp",
    "coverIndex": 0
  },
  {
    "id": "g3-rcc-apartment-building-india",
    "title": "G+3 RCC Apartment Building",
    "city": "India",
    "category": "Residential & ADU",
    "featured": false,
    "size": "Ground + 3 · 3.2 m storey height · lift core",
    "summary": "ETABS analysis, SAFE foundation design and RCDC detailing for a four-storey RCC apartment block with a lift core and staircase.",
    "scope": [
      "ETABS model of the frame, slabs and lift core with wall, slab and staircase loads",
      "Shear force, bending moment, axial force and support-reaction results",
      "Column longitudinal reinforcement and reinforcement-percentage check from the design model",
      "Isolated footings in SAFE with footing schedule, layout and sections",
      "Column schedule (230 × 450 mm columns and a 640 × 2970 mm lift-core pier), beam, slab and staircase reinforcement details",
      "Design basis: M25 concrete, Fe 500 / Fe 500D bars; 150 mm slabs, 230 × 300 mm beams; staircase dead load 7 kN/m², live load 3 kN/m²; main wall 13.89 kN/m, partition 6.09 kN/m"
    ],
    "codes": [
      "IS 456:2000",
      "IS 875",
      "IS 1893 (Part 1):2016",
      "IS 13920:2016",
      "IS 1786"
    ],
    "software": [
      "ETABS",
      "SAFE",
      "RCDC"
    ],
    "sheets": [
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/cover.webp",
        "caption": "Rendered exterior and interior views",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/s01.webp",
        "caption": "Grid plan and 3D model",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/s02.webp",
        "caption": "Shear force and bending moment diagrams",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/s03.webp",
        "caption": "Axial forces and support reactions",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/s04.webp",
        "caption": "Column longitudinal reinforcement and reinforcement percentage",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/s05.webp",
        "caption": "Footing schedule, layout and sections",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/s06.webp",
        "caption": "Column schedule and details",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/s07.webp",
        "caption": "Column and lift-core cross-section schedule",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/s08.webp",
        "caption": "Beam details and schedule",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/s09.webp",
        "caption": "Slab sections and schedule",
        "portrait": false
      },
      {
        "src": "assets/projects/g3-rcc-apartment-building-india/s10.webp",
        "caption": "Staircase details and slab layout",
        "portrait": false
      }
    ],
    "cover": "assets/projects/g3-rcc-apartment-building-india/cover.webp",
    "coverIndex": 0
  },
  {
    "id": "master-bedroom-addition-spring-valley",
    "title": "Master Bedroom Addition with CMU Foundation",
    "city": "Spring Valley, CA",
    "category": "Additions, Remodels & Repairs",
    "size": "Second-story addition",
    "summary": "Structural design for a master bedroom addition attached to an existing single-family home, with a new CMU foundation tied into the existing footings.",
    "scope": [
      "New CMU foundation: 8\"×16\" block on 18\"W × 10\"D continuous footing, (3) #4 top and bottom, #4 @ 18\" O.C. transverse",
      "Tie-in to existing footings; field-verification notes for existing conditions",
      "Shear wall design (SW1–SW3) and framing coordination with the existing structure",
      "Anchor bolt layout: 5/8\"Ø × 10\" @ 6'-0\" O.C. with 3\"×3\"×0.229\" plate washers"
    ],
    "codes": [
      "2022 CBC / CRC",
      "ACI 318",
      "NDS"
    ],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/master-bedroom-addition-spring-valley/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/master-bedroom-addition-spring-valley/s01.webp",
        "caption": "Foundation plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/master-bedroom-addition-spring-valley/s02.webp",
        "caption": "Wall layout plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/master-bedroom-addition-spring-valley/s03.webp",
        "caption": "Roof framing plan · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/master-bedroom-addition-spring-valley/s04.webp",
        "caption": "Typical section details · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/master-bedroom-addition-spring-valley/s05.webp",
        "caption": "Typical wall details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/master-bedroom-addition-spring-valley/s06.webp",
        "caption": "Typical details · S-6",
        "portrait": false
      },
      {
        "src": "assets/projects/master-bedroom-addition-spring-valley/s07.webp",
        "caption": "Calculation sheet · wood shear wall design (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "whole-house-remodel-la-jolla",
    "title": "Whole-House Remodel with HSS Steel Posts",
    "city": "La Jolla, CA",
    "category": "Additions, Remodels & Repairs",
    "featured": true,
    "size": "Multi-level residence + carport",
    "summary": "Structural engineering for a single-family remodel on an irregular lot: new foundations, steel posts, bearing and shear walls, and a new carport.",
    "scope": [
      "Foundation plan with HSS 6×6×¼\" steel posts on isolated pad footings (F1 24\"×24\"×12\", F3 15\"×18\", F4 48\"×48\"×18\" with (3) #4 continuous top and bottom)",
      "New slab on grade; bearing wall layout (2BW1–2BW3) and shear wall marks",
      "Continuous load path to the foundation; tie-ins to existing footings with field verification",
      "Master suite, 1st and 2nd floor wall and framing plans",
      "New carport: foundation, layout and framing"
    ],
    "codes": [
      "2022 CBC / CRC",
      "ACI 318",
      "AISC 360",
      "NDS"
    ],
    "software": [
      "AutoCAD",
      "Tekla Tedds",
      "Enercalc"
    ],
    "cover": "assets/projects/whole-house-remodel-la-jolla/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/whole-house-remodel-la-jolla/s01.webp",
        "caption": "Foundation plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/whole-house-remodel-la-jolla/s02.webp",
        "caption": "Proposed 1st floor wall layout · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/whole-house-remodel-la-jolla/s03.webp",
        "caption": "Proposed 1st floor framing plan · S-3.1",
        "portrait": false
      },
      {
        "src": "assets/projects/whole-house-remodel-la-jolla/s04.webp",
        "caption": "Proposed 2nd floor framing plan · S-4.1",
        "portrait": false
      },
      {
        "src": "assets/projects/whole-house-remodel-la-jolla/s05.webp",
        "caption": "Roof framing details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/whole-house-remodel-la-jolla/s06.webp",
        "caption": "Carport foundation plan · S-7",
        "portrait": false
      },
      {
        "src": "assets/projects/whole-house-remodel-la-jolla/s07.webp",
        "caption": "Carport framing plan · S-7.2",
        "portrait": false
      },
      {
        "src": "assets/projects/whole-house-remodel-la-jolla/s08.webp",
        "caption": "Calculation sheet (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "garage-addition-la-mesa",
    "title": "Attached Garage Addition",
    "city": "La Mesa, CA",
    "category": "Additions, Remodels & Repairs",
    "size": "20′ × 24′ · 472 sq ft",
    "summary": "A new 20′×24′ garage added to the side of an existing house, with a new foundation and roof framing tied into the existing structure.",
    "scope": [
      "Wall layout, foundation and roof framing plans",
      "Wall elevations and typical wall details",
      "Section and connection details"
    ],
    "codes": [
      "2022 CRC",
      "NDS 2018",
      "ASCE 7-22",
      "ACI 318-14"
    ],
    "software": [
      "Tekla Tedds",
      "AutoCAD"
    ],
    "cover": "assets/projects/garage-addition-la-mesa/cover.webp",
    "coverIndex": 1,
    "sheets": [
      {
        "src": "assets/projects/garage-addition-la-mesa/s01.webp",
        "caption": "Wall layout plan · S-1",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-addition-la-mesa/s02.webp",
        "caption": "Foundation plan · S-2",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-addition-la-mesa/s03.webp",
        "caption": "Roof framing details · S-3",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-addition-la-mesa/s04.webp",
        "caption": "Wall elevations · S-4",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-addition-la-mesa/s05.webp",
        "caption": "Typical wall details · S-4.1",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-addition-la-mesa/s06.webp",
        "caption": "Typical section details · S-5",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-addition-la-mesa/s07.webp",
        "caption": "Typical details · S-6",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-addition-la-mesa/s08.webp",
        "caption": "Calculation sheet (Tekla Tedds)",
        "portrait": true
      }
    ]
  },
  {
    "id": "covered-patio-addition-michigan",
    "title": "Covered Patio Addition with LVL Beams",
    "city": "Macomb, MI",
    "category": "Additions, Remodels & Repairs",
    "size": "23′ × 14′-6″ patio roof",
    "summary": "A new patio roof tied to an existing house, framed with 6×6 posts, triple LVL beams and an 8:12 engineered-wood roof.",
    "scope": [
      "Foundation plan with new footings and reuse of existing footings",
      "(3) 1¾\" × 16\" LVL beams on 6×6 posts with Simpson post bases and caps",
      "(2) 2×10 ridge beam and engineered-wood rafters at an 8:12 slope",
      "House / roof interface and typical connection details"
    ],
    "codes": [],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/covered-patio-addition-michigan/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/covered-patio-addition-michigan/s01.webp",
        "caption": "Patio roof framing plan",
        "portrait": false
      },
      {
        "src": "assets/projects/covered-patio-addition-michigan/s02.webp",
        "caption": "Patio foundation plan",
        "portrait": false
      },
      {
        "src": "assets/projects/covered-patio-addition-michigan/s03.webp",
        "caption": "Patio layout plan",
        "portrait": false
      },
      {
        "src": "assets/projects/covered-patio-addition-michigan/s04.webp",
        "caption": "Sections",
        "portrait": false
      },
      {
        "src": "assets/projects/covered-patio-addition-michigan/s05.webp",
        "caption": "Typical connection details",
        "portrait": false
      }
    ]
  },
  {
    "id": "clear-span-beam-oregon",
    "title": "Clear-Span LVL Beam Installation",
    "city": "Oregon",
    "category": "Additions, Remodels & Repairs",
    "size": "7″ × 11⅞″ LVL flush beam",
    "summary": "A flush LVL beam that opens up a first-floor living space, with bearing on concrete and masonry walls and full connection details on a single sheet.",
    "scope": [
      "Clear-span beam keyplan, Sections A-A and B-B",
      "7\" × 11⅞\" LVL flush beam with Simpson HUC710 hangers and 4×4×¼\" steel angles",
      "6×8 header details; Ø5/8\" thru-bolts and expansion-bolt anchorage",
      "Code compliance summary (OSSC 2018 / IBC 2018, SDC A) and load combinations"
    ],
    "codes": [
      "OSSC / IBC 2018",
      "ASCE 7-16",
      "NDS-2018",
      "ACI 318-14"
    ],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/clear-span-beam-oregon/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/clear-span-beam-oregon/s01.webp",
        "caption": "Clear-span beam keyplan, sections and notes",
        "portrait": false
      }
    ]
  },
  {
    "id": "garage-building-repair",
    "title": "Six-Bay Garage Building Repair",
    "city": "",
    "category": "Additions, Remodels & Repairs",
    "size": "Two levels · six garages",
    "summary": "A repair scheme for a two-level, six-bay garage building: damaged wall sections and framing are removed and replaced, with new floor joists and strapping.",
    "scope": [
      "Wall layout plan identifying damaged wall sections and framing to be replaced",
      "Wall elevation details with 1-hr rated assemblies (UL U465)",
      "New 2×10 floor joists @ 16\" O.C. and roof framing at 2×10 @ 24\" O.C.",
      "Simpson MST / coil strapping and shear-transfer details"
    ],
    "codes": [],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/garage-building-repair/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/garage-building-repair/s01.webp",
        "caption": "Wall layout plan · S1",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-building-repair/s02.webp",
        "caption": "Wall elevation details · S2",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-building-repair/s03.webp",
        "caption": "Framing plans · S3",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-building-repair/s04.webp",
        "caption": "Framing plan and details · S4",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-building-repair/s05.webp",
        "caption": "Typical details · S5",
        "portrait": false
      },
      {
        "src": "assets/projects/garage-building-repair/s06.webp",
        "caption": "Roof framing plans · S6",
        "portrait": false
      }
    ]
  },
  {
    "id": "lvl-beam-post-installation-kentucky",
    "title": "Deck Beam & Post Replacement with LVL",
    "city": "Kentucky",
    "category": "Additions, Remodels & Repairs",
    "size": "(2) 1¾″ × 7¼″ LVL beams on 6×6 posts",
    "summary": "Replacement beams and posts for an existing deck: LVL beams on 6×6 posts with Simpson post caps and bases on precast concrete deck blocks, to the Kentucky building code.",
    "scope": [
      "(2) 1¾″ × 7¼″ LVL beam with staggered nailing and beam connection detail",
      "6×6 posts with Simpson CC66 caps and IPC6Z bases on precast concrete deck blocks",
      "Foundation plan and installation details",
      "Design criteria: 2015 IBC / 2018 Kentucky Building Code, ASCE 7-10, 115 mph wind, 15 psf ground snow"
    ],
    "codes": [
      "2015 IBC / 2018 KBC",
      "ASCE 7-10",
      "NDS",
      "ACI 318-14"
    ],
    "software": [
      "AutoCAD",
      "Tekla Tedds"
    ],
    "cover": "assets/projects/lvl-beam-post-installation-kentucky/cover.webp",
    "coverIndex": 0,
    "sheets": [
      {
        "src": "assets/projects/lvl-beam-post-installation-kentucky/s01.webp",
        "caption": "Beam installation, foundation plan and details · S1.1",
        "portrait": false
      },
      {
        "src": "assets/projects/lvl-beam-post-installation-kentucky/s02.webp",
        "caption": "General structural notes · S1.0",
        "portrait": false
      }
    ]
  },
  {
    "id": "etabs-four-cell-octagonal-structure",
    "title": "Four-Cell Octagonal Concrete Structure — ETABS Model",
    "city": "",
    "category": "Structural Analysis & Modelling",
    "featured": false,
    "size": "Four octagonal cells on a braced column frame",
    "summary": "ETABS model of four interconnected octagonal concrete cells supported on a braced column frame, with an adjoining truck-shade level at 22 ft.",
    "scope": [
      "3D model of the octagonal cell walls as piers, the supporting column frame and the truck-shade roof",
      "Pier longitudinal reinforcing areas reviewed in plan at the truck-shade level (Z = 22 ft)",
      "Dead-load displacement check of the full structure"
    ],
    "codes": [],
    "software": [
      "ETABS 18"
    ],
    "sheets": [
      {
        "src": "assets/projects/etabs-four-cell-octagonal-structure/cover.webp",
        "caption": "ETABS model — plan and 3D views",
        "portrait": false
      },
      {
        "src": "assets/projects/etabs-four-cell-octagonal-structure/s01.webp",
        "caption": "Plan at Z = 22 ft — pier longitudinal reinforcing areas",
        "portrait": true
      },
      {
        "src": "assets/projects/etabs-four-cell-octagonal-structure/s02.webp",
        "caption": "3D view — dead-load displacements",
        "portrait": true
      }
    ],
    "cover": "assets/projects/etabs-four-cell-octagonal-structure/cover.webp",
    "coverIndex": 0
  },
  {
    "id": "multi-storey-frame-shear-wall-model",
    "title": "Multi-Storey RC Frame with Shear Walls — 3D Model",
    "city": "",
    "category": "Structural Analysis & Modelling",
    "featured": false,
    "size": "5 × 4 bays · spans up to 7.5 m",
    "summary": "3D analysis model of a multi-storey concrete frame with floor diaphragms meshed as shells and shear walls at the core and perimeter.",
    "scope": [
      "Grid A–F (4.75 / 7 / 7 / 7 / 4.5 m) by grid 1–5 (7.5 / 7.5 / 7.5 / 4.5 m)",
      "Floor slabs meshed as shell elements; vertical wall elements at the core and on the perimeter",
      "Deformed-shape review of the floor plates under load"
    ],
    "codes": [],
    "software": [],
    "sheets": [
      {
        "src": "assets/projects/multi-storey-frame-shear-wall-model/cover.webp",
        "caption": "Plan and 3D deformed shape",
        "portrait": false
      },
      {
        "src": "assets/projects/multi-storey-frame-shear-wall-model/s01.webp",
        "caption": "Typical floor plan and grid",
        "portrait": true
      },
      {
        "src": "assets/projects/multi-storey-frame-shear-wall-model/s02.webp",
        "caption": "3D model — deformed floor plates",
        "portrait": false
      }
    ],
    "cover": "assets/projects/multi-storey-frame-shear-wall-model/cover.webp",
    "coverIndex": 0
  },
  {
    "id": "slab-fe-design-circular-opening",
    "title": "Slab Finite-Element Design Around a Circular Opening",
    "city": "",
    "category": "Structural Analysis & Modelling",
    "featured": false,
    "size": "Single slab panel with circular opening",
    "summary": "Finite-element slab design showing enveloped bottom-reinforcement intensity around a circular opening near a slab corner.",
    "scope": [
      "Slab meshed into finite elements with the opening modelled",
      "Enveloped bottom-reinforcement intensity contours (in²/ft), Direction 1",
      "Identification of reinforcement concentration at the opening edge for detailing"
    ],
    "codes": [],
    "software": [],
    "sheets": [
      {
        "src": "assets/projects/slab-fe-design-circular-opening/cover.webp",
        "caption": "Bottom reinforcement intensity (enveloping), Direction 1",
        "portrait": false
      }
    ],
    "cover": "assets/projects/slab-fe-design-circular-opening/cover.webp",
    "coverIndex": 0
  },
  {
    "id": "rc-continuous-beam-en1992",
    "title": "RC Continuous Beam with Cantilevers — EN 1992 Design",
    "city": "",
    "category": "Structural Analysis & Modelling",
    "featured": false,
    "size": "3 spans: 2.1 m cantilever · 6.5 m · 1.8 m cantilever",
    "summary": "Analysis and design of a 250 × 500 mm reinforced-concrete beam over two supports with cantilevers at both ends, to EN 1992-1-1:2004.",
    "scope": [
      "Geometry: 6.5 m main span with 2.1 m and 1.8 m cantilevers, R 250 × 500 section, C30 concrete",
      "Loading: permanent 20.3 kN/m and variable 15.5 kN/m plus self weight",
      "Strength combination 1.35G + 1.5Q + 1.5RQ with deflection results",
      "Member analysis and design in Tekla Tedds"
    ],
    "codes": [
      "EN 1992-1-1:2004"
    ],
    "software": [
      "Tekla Tedds"
    ],
    "sheets": [
      {
        "src": "assets/projects/rc-continuous-beam-en1992/cover.webp",
        "caption": "Analysis page — geometry, loading and deflection",
        "portrait": true
      }
    ],
    "cover": "assets/projects/rc-continuous-beam-en1992/cover.webp",
    "coverIndex": 0
  }
];
